In [ ]:
import numpy as np
arr=np.array(2)
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('number of dimension:',nd)

2
1
()
<class 'numpy.ndarray'>
number of dimension: 0


In [ ]:
#1 dimensinal array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('number of dimension:',nd)

[1 2 3 4 5]
5
(5,)
<class 'numpy.ndarray'>
number of dimension: 1


In [ ]:
#2 dimensional array
arr=np.array([[1,2,8],[3,4,9],[8,6,7]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('number of dimension:',nd)

[[1 2 8]
 [3 4 9]
 [8 6 7]]
9
(3, 3)
<class 'numpy.ndarray'>
number of dimension: 2


In [ ]:
arr=np.array([[2,0,1],[1,2]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print('number of dimension:',nd)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [ ]:
#array indexing
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st dim:',arr[0,1])


2nd element on 1st dim: 2


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd dim:',arr[1,4])

5th element on 2nd dim: 10


In [ ]:
#accsee the third element of seconndary#of the first array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
print(arr)
print()

6
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]



In [ ]:
import numpy as np
arr=np.array([1,3,5,7,9])
sum=arr[0]+arr[2]
diff=arr[3]-arr[2]
product=arr[1]*arr[3]
div=arr[4]/arr[2]
print("sum of 2 numbers=",sum)
print("difference of 2 numbers=",diff)
print("product of 2 numbers=",product)
print("division of 2 numbers=",div)

sum of 2 numbers= 6
difference of 2 numbers= 2
product of 2 numbers= 21
division of 2 numbers= 1.8


In [ ]:
#slicing of 1 dimension arrray
import numpy as np
arr=np.array([2,4,6,8,10,12,14,16])
print(arr[3:6])
print(arr[:5])
print(arr[2:])
print(arr[-5:-1])

[ 8 10 12]
[ 2  4  6  8 10]
[ 6  8 10 12 14 16]
[ 8 10 12 14]


In [ ]:
#reshaping
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
import numpy as np
np.arange(1,14,4)

array([ 1,  5,  9, 13])

In [ ]:
#element wise arithmetic operations
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1@arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print()
concatenated_arr=np.concatenate((arr1,arr2),axis=0)
print(concatenated_arr)
print()
concatenated_arr=np.concatenate((arr1,arr2),axis=1)
print(concatenated_arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
print(arr)
print("{originalarr.shape:",arr.shape)
print()
transposed_arr=arr.transpose()
print(transposed_arr)
print("transposed_arr.shape:",transposed_arr.shape)
print()
flatened_arr=arr.flatten()
print(flatened_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
{originalarr.shape: (12,)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
transposed_arr.shape: (12,)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
