In [ ]:
import numpy as np
crop_yields = np.array([
    [12.5, 13.2, 14.1, 13.8, 15.2],
    [13.5, 14.2, 15.1, 14.8, 15.8],
    [14.6, 14.8, 15.3, 14.9, 16.4],
    [14.8, 15.1, 15.6, 15.3, 16.8]
])
print('crop_yields array(tons)')
print(crop_yields)
print(f'\nshape:{crop_yields.shape}')
print(f'data type:{crop_yields.dtype}')
print(f'total elements:{crop_yields.size}')
print(f'number of dimensions:{crop_yields.ndim}')

crop_yields array(tons)
[[12.5 13.2 14.1 13.8 15.2]
 [13.5 14.2 15.1 14.8 15.8]
 [14.6 14.8 15.3 14.9 16.4]
 [14.8 15.1 15.6 15.3 16.8]]

shape:(4, 5)
data type:float64
total elements:20
number of dimensions:2


In [ ]:
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f'\n total production:{total_yield}tons')
print(f'\n average production per farm:{avg_yield_per_farm}tons')
print(f'\n average production per season:{avg_yield_per_season}tons')
print(f'\n maximum production:{max_yield}tons')
print(f'\nminimum yield:{min_yield}tons')


 total production:295.8tons

 average production per farm:[13.76 14.68 15.2  15.52]tons

 average production per season:[13.85  14.325 15.025 14.7   16.05 ]tons

 maximum production:16.8tons

minimum yield:12.5tons


In [ ]:
best_farm=