In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv("/content/Product_purchase (20).csv")
df

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [ ]:
x=df.iloc[:,[2,3]].values
y=df.iloc[:,4].values
print(df.columns[[2,3]])
print(df.head(3))

Index(['Age', 'EstimatedSalary'], dtype='object')
    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',max_depth=None,
                             min_samples_split=5,min_samples_leaf=2)
model.fit(x_train,y_train)
print(model)
y_pred_dec=model.predict(x_test)
y_pred_dec
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_dec)
print(cm)

from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred_dec)
print(acc)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)
[[66  2]
 [ 6 26]]
0.92


In [ ]:
from sklearn.linear_model import LogisticRegression
modellr=logisticRegression(random_state=0)
modellr.fit(x_train,y_train)
print(modellr.)


SyntaxError: invalid syntax (3044067689.py, line 4)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFmodel=RandomForestClassifier(n_estimators=200,criterion="entropy",random_state=0)
RFmodel.fit(x_train,y_train)

y_pred_rf=RFmodel.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_rf)
print(cm)

from sklearn.metrics import accuracy_score
print("Random Forest", accuracy_score(y_test,y_pred_rf))

[[64  4]
 [ 4 28]]
Random Forest 0.92


In [ ]:
from sklearn.naive_bayes import GaussianNB
nbmodel=GaussianNB()
nbmodel.fit(x_train,y_train)

y_pred_nb=nbmodel.predict(x_test)
cmnb=confusion_matrix(y_test,y_pred_nb)
print(cmnb)
accuracy_nb=accuracy_score(y_test,y_pred_nb)
print("Accuracy:",accuracy_nb)

[[65  3]
 [ 7 25]]
Accuracy: 0.9


In [ ]:
rn.svm

In [ ]:
from sklearn.naive_bayes import GaussianNB
nbmodel=GaussianNB()
nbmodel.fit(x_train,y_train)

y_pred_nb=nbmodel.predict(x_test)
cmnb=confusion_matrix(y_test,y_pred_nb)
print(cmnb)
accuracy_nb=accuracy_score(y_test,y_pred_nb)
print("Accuracy:",accuracy_nb)

[[65  3]
 [ 7 25]]
Accuracy: 0.9


In [ ]:
from sklearn.svm import SVC
model=SVC(kernel="poly",degree=3)
model.fit(x_train,y_train)
print(model)

SVC(kernel='poly')


In [ ]:
y_pred_svm=model.predict(x_test)
print(y_pred_svm)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0]


In [ ]:
from sklearn.metrics import confusion_matrix
cm_svc=confusion_matrix(y_test,y_pred_svm)
print(cm_svc)

[[67  1]
 [13 19]]
